#	$OpenBSD: pf.conf,v 1.55 2017/12/03 20:40:04 sthen Exp $
#
# See pf.conf(5) and /etc/examples/pf.conf

# Macros
ext_if = "em0"

# Options
set skip on lo

# Default Policy
block all

# Port build user does not need network
block return out log proto {tcp udp} user _pbuild

# Outbound
pass out on $ext_if proto { tcp udp icmp } all keep state

# Inbound SSH
pass in on $ext_if proto tcp to port 22
pass in on $ext_if proto {tcp udp} to port 53
pass in on $ext_if proto tcp to port 636
